## MECE Table

| Member     | Task Description                                                                                      |
|------------|--------------------------------------------------------------------------------------------------------|
| Aparna Jayakumar Resmi    | 1: Count records with dates not using alphabets.                                                      |
|       | B1: Perform stemming using Porter Stemmer. Count unique words before and after stemming.              |
| Stephen David Chitilapalli Mathew    | 2: Count records with a word starting with "w".                                                       |
|      | B2: Perform lemmatization using NLTK lemmatizer. Count unique words before and after lemmatization.   |
| Shabda Kafle    | 3: Count records with words that start with an alphabet and are not URLs.                            |
|       | B3: Compare the change in word frequencies after stemming and lemmatization. Identify top 10 words.   |
| Jeffin John Abraham     | 4: Count records containing specific emojis (e.g., :D, :), ;), :P).                                   |
|       | 8: Count the total number of hashtags across all tweets.                                              |
| Neha Tamang      | 5: Count records with decimal numbers.                                                                |
|         | B4: Analyze the change in word frequencies after normalization and stop-word removal.                 |
| Anirudhra Budhathoki  | 6: Count the total number of IP addresses.                                                            |
| Devanshi Adhikari   | 7: Count records with a new line.                                                                     |
| Arjun Kumar      | 9: Substitute non-alphanumeric characters with a newline.                                             |
| Sumith Padma Padmasree Vijayapadman     | 10: Count the total number of URLs across all tweets.                                                 |


### A: For the given data write and run regex

Q1. How many records have a date that is expressed without using alphabets?

In [1]:
import pandas as pd
import re
data = pd.read_csv("Data.csv")
data.head()

# Comprehensive regex pattern for dates
date_pattern = r"""
    # Match dates with slashes, dashes or dots
    (?:
        # MM/DD/YY or MM/DD/YYYY (American format)
        (?:0?[1-9]|1[0-2])[/\-\.](?:0?[1-9]|[12][0-9]|3[01])[/\-\.](?:19|20)?\d\d
        |
        # DD/MM/YY or DD/MM/YYYY (European format)
        (?:0?[1-9]|[12][0-9]|3[01])[/\-\.](?:0?[1-9]|1[0-2])[/\-\.](?:19|20)?\d\d
        |
        # YYYY/MM/DD (ISO format)
        (?:19|20)\d\d[/\-\.](?:0?[1-9]|1[0-2])[/\-\.](?:0?[1-9]|[12][0-9]|3[01])
        |
        # YYYYMMDD (Compact ISO format)
        (?:19|20)\d\d(?:0[1-9]|1[0-2])(?:0[1-9]|[12][0-9]|3[01])
    )
"""

# Compiling the regex pattern first
compiled_pattern = re.compile(date_pattern, re.VERBOSE)

# Using a lambda function to apply the compiled pattern
date_mask = data['Data'].apply(lambda x: bool(compiled_pattern.search(str(x))) if pd.notna(x) else False)

# Counting the instances that match
date_count = date_mask.sum()
if date_count > 0:
    # Displaying all matching records
    date_records = data[date_mask]
    print("Records with dates (no alphabets):")
    display(date_records)
    print("\n")
print("Total number of records with dates expressed without alphabets:", date_count)

Total number of records with dates expressed without alphabets: 0


There is no records with just numeric dates

Q2. How many records have a word starting with the letter “w”?

In [2]:
import pandas as pd
import re

# Load the CSV file
df = pd.read_csv("Data.csv")

Pattern = r"\b[wW]\w*"
words_with_w = df['Data'].str.contains(Pattern,regex=True)
words_with_w.sum()
print("Number of records with a word starting with 'w':", words_with_w.sum())

Number of records with a word starting with 'w': 3591


Number of records with a word starting with 'w': 3591

Q3. How many records make a word that starts with an alphabet and is not a URL?

In [3]:
# Pattern to detect URLs
url_pattern = r'http[s]?://\S+'

# Pattern to find words that start with an alphabet
word_pattern = r'\b[a-zA-Z]\w*'
def is_valid_text(text):
    has_url = re.search(url_pattern, text)
    has_word = re.search(word_pattern, text)
    return has_word and not has_url
df['is_valid'] = df['Data'].apply(is_valid_text)
valid_count = df['is_valid'].sum()
print("Number of valid records:", valid_count)

Number of valid records: 7301


Number of valid records: 7301


Q4. How many tweets contain one of these emojis :), :D, ;), :P?

In [4]:
emoji_pattern = r":\)|:D|;\)|:P"


emoji_tweet_count = df['Data'].astype(str).apply(lambda x: bool(re.search(emoji_pattern, x))).sum()

print("Number of tweets that contain at least one of the emojis :), :D, ;), :P:", emoji_tweet_count)

Number of tweets that contain at least one of the emojis :), :D, ;), :P: 18


Q5. How many records contain a decimal number?

In [5]:
# Combine all columns in each row into a single string
combined_rows = df.astype(str).agg(' '.join, axis=1)
# Define regex pattern for decimal numbers
pattern = r'\d+\.\d+'
# Count how many records contain a decimal number
decimal_count = combined_rows.str.contains(pattern).sum()

print(f"Number of records containing a decimal number: {decimal_count}")

Number of records containing a decimal number: 27


Number of records containing a decimal number: 27


Q6. What is the total number of ip addresses across all the records?

In [6]:
import pandas as pd
import re

# Step 2: Load the CSV file (assuming it's named Data.csv)
df = pd.read_csv('Data.csv')

# Step 3: Define regex pattern for IPv4 addresses
ip_pattern = r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'

# Step 4: Apply regex to find IP addresses in each row
all_ips = df['Data'].apply(lambda x: re.findall(ip_pattern, str(x)))

# Step 5: Count total IP addresses
total_ips = sum(len(ips) for ips in all_ips)

# Step 6: Print the result
print("Total number of IP addresses:", total_ips)

Total number of IP addresses: 0


Total number of IP addresses: 0


Q7. How many records have a new line?

In [7]:
newline_count = df['Data'].str.contains(r'\n').sum()
print(f"records new line have : {newline_count}")

records new line have : 1211


records new line have : 1211


Q8. What is the total number of hashtags across all these tweets?

In [8]:
import re
hashtag_pattern = r"#\w+"
hashtag_count = df['Data'].astype(str).apply(lambda x: len(re.findall(hashtag_pattern, x))).sum()
print("Total number of hashtags across all tweets:", hashtag_count)

Total number of hashtags across all tweets: 2924


Total number of hashtags across all tweets: 2924


Q9. What is the code to substitute all non-alphanumeric characters with a new line?

In [9]:
import pandas as pd
import re

# Load the CSV File
df = pd.read_csv("Data.csv")

# Replace all non-alphanumeric characters with a newline
df['Substituted'] = df['Data'].apply(lambda x: re.sub(r'[^A-Za-z0-9]', '\n', str(x)))

# Display the first few modified entries
df[['Data', 'Substituted']].head()

# To print the first row with real newlines
print(df['Substituted'].iloc[0])

Watch
or
listen
live
weekdays
at
8
30am
MT
at
ryanjespersen
com

Subscribe
via
YouTube
or
your
favourite
podcast
app


RealTalkRJ


Q10. What is the total number of URLs across all tweets?

In [10]:
# Define a regular expression pattern to match URLs
url_pattern = r"http[s]?://\S+"

# Count the number of URLs in each tweet and sum them up
total_urls = df['Data'].str.count(url_pattern).sum()

print("Total number of URLs across all tweets:",total_urls)

Total number of URLs across all tweets: 4


Total number of URLs across all tweets: 4

### B: Perform stemming and lemmatization

Q1. Use porter stemmer to run stemming. Count the number of unique
words/tokens before and after stemming


In [11]:
import pandas as pd
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from collections import Counter

nltk.download('punkt')
nltk.download('punkt_tab')

porter = PorterStemmer()

# Function to clean and tokenize text
def clean_and_tokenize(text):
    if not isinstance(text, str):
        return []

    # Converting to lowercase and remove special characters
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    tokens = word_tokenize(text)

    return tokens

# Function to stem tokens
def stem_tokens(tokens):
    return [porter.stem(token) for token in tokens]

# Processing the entire dataset
all_tokens_before = []
all_tokens_after = []

# Applying tokenization and stemming to each row
for text in data['Data']:
    tokens = clean_and_tokenize(text)
    all_tokens_before.extend(tokens)

    stemmed_tokens = stem_tokens(tokens)
    all_tokens_after.extend(stemmed_tokens)

# Count unique tokens before and after stemming
unique_before = len(set(all_tokens_before))
unique_after = len(set(all_tokens_after))

# Get the total number of tokens
total_tokens = len(all_tokens_before)

#Results
print(f"Total number of tokens: {total_tokens}")
print(f"Number of unique tokens before stemming: {unique_before}")
print(f"Number of unique tokens after stemming: {unique_after}")
print(f"Reduction in vocabulary size: {unique_before - unique_after} words ({((unique_before - unique_after) / unique_before * 100):.2f}%)")

# Most common words before and after stemming
print("\nMost common words before stemming:")
print(Counter(all_tokens_before).most_common(10))

print("\nMost common words after stemming:")
print(Counter(all_tokens_after).most_common(10))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


Total number of tokens: 114095
Number of unique tokens before stemming: 8137
Number of unique tokens after stemming: 6780
Reduction in vocabulary size: 1357 words (16.68%)

Most common words before stemming:
[('and', 3516), ('the', 2859), ('of', 2223), ('to', 2179), ('a', 1555), ('in', 1539), ('for', 1507), ('alberta', 952), ('is', 922), ('my', 895)]

Most common words after stemming:
[('and', 3516), ('the', 2859), ('of', 2223), ('to', 2179), ('a', 1555), ('in', 1545), ('for', 1507), ('alberta', 1061), ('is', 922), ('my', 895)]


Q2. Perform lemmatization using NLTK lemmatizer. Count the number of
unique words/tokens before and after lemmatization

In [12]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download required NLTK data files (only needed once)
# Added the download for 'punkt_tab' which is required by word_tokenize internally
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab') # Download the punkt_tab resource

# Load the CSV file
df = pd.read_csv("Data.csv")

# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Combine all text data into a single string
all_text = ' '.join(df['Data'].dropna().astype(str))

# Tokenize the text
tokens = word_tokenize(all_text)

# Count unique tokens before lemmatization
unique_before = set(tokens)

# Lemmatize each token
lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]

# Count unique tokens after lemmatization
unique_after = set(lemmatized_tokens)

# Print the counts
print("Unique tokens before lemmatization:", len(unique_before))
print("Unique tokens after lemmatization:", len(unique_after))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


Unique tokens before lemmatization: 10590
Unique tokens after lemmatization: 10227


Q3. Compare the change in word frequencies from stemming and
lemmatization. Which are the top 10 words after stemming/lemmatization

In [13]:
#Importing Required Libraries
import pandas as pd
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk import pos_tag
from collections import Counter
# Downloading Required NLTK Resources
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('omw-1.4')

#Initializing Stemmer and Lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
#POS Mapping Function for Lemmatization
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # default
#Define Tokenization + Transformation Functions
def stem_text(text):
    tokens = word_tokenize(str(text).lower())
    return [stemmer.stem(word) for word in tokens]

def lemmatize_text(text):
    tokens = word_tokenize(str(text).lower())
    pos_tags = pos_tag(tokens)
    return [lemmatizer.lemmatize(word, get_wordnet_pos(tag)) for word, tag in pos_tags]
#Applying Stemming and Lemmatization
df['Stemmed_Tokens'] = df['Data'].apply(stem_text)
df['Lemmatized_Tokens'] = df['Data'].apply(lemmatize_text)
#Flatten Word Lists for Frequency Count
all_stemmed_words = [word for row in df['Stemmed_Tokens'] for word in row]
all_lemmatized_words = [word for row in df['Lemmatized_Tokens'] for word in row]
#Calculate Word Frequencies
stemmed_freq = Counter(all_stemmed_words)
lemmatized_freq = Counter(all_lemmatized_words)
#Displaying Top 10 Most Frequent Words
print("🔹 Top 10 Words After Stemming:")
for word, count in stemmed_freq.most_common(10):
    print(f"{word}: {count}")

print("\n🔹 Top 10 Words After Lemmatization:")
for word, count in lemmatized_freq.most_common(10):
    print(f"{word}: {count}")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


🔹 Top 10 Words After Stemming:
.: 10145
,: 9314
and: 3514
#: 2936
the: 2859
of: 2223
to: 2179
&: 1699
@: 1620
a: 1551

🔹 Top 10 Words After Lemmatization:
.: 10145
,: 9314
and: 3514
#: 2936
the: 2859
of: 2223
to: 2179
be: 2111
a: 1718
&: 1699


Q4. What is the change in word frequencies if normalization is done after
stop word removal

In [14]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk import pos_tag
from nltk.stem import PorterStemmer, WordNetLemmatizer
from collections import Counter
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

# Text Processing Class
class TextNormalizer:
    def __init__(self):
        self.stop_words = set(stopwords.words('english'))
        self.stemmer = PorterStemmer()
        self.lemmatizer = WordNetLemmatizer()

    def tokenize(self, text):
        return word_tokenize(str(text).lower())

    def remove_stopwords(self, tokens):
        return [t for t in tokens if t.isalnum() and t not in self.stop_words]

    def stem(self, tokens):
        return [self.stemmer.stem(t) for t in tokens]

    def lemmatize(self, tokens):
        tagged = pos_tag(tokens)
        return [self.lemmatizer.lemmatize(word, self.get_wordnet_pos(tag)) for word, tag in tagged]

    def get_wordnet_pos(self, tag):
        if tag.startswith('J'):
            return wordnet.ADJ
        elif tag.startswith('V'):
            return wordnet.VERB
        elif tag.startswith('N'):
            return wordnet.NOUN
        elif tag.startswith('R'):
            return wordnet.ADV
        return wordnet.NOUN  # default fallback

    def normalize(self, text, method='stem'):
        tokens = self.tokenize(text)
        tokens = self.remove_stopwords(tokens)
        if method == 'stem':
            return self.stem(tokens)
        elif method == 'lemma':
            return self.lemmatize(tokens)
        else:
            raise ValueError("Method must be either 'stem' or 'lemma'.")
df = pd.read_csv("Data.csv")
normalizer = TextNormalizer()
df['Stemmed_NoStop'] = df['Data'].apply(lambda x: normalizer.normalize(x, method='stem'))
df['Lemmatized_NoStop'] = df['Data'].apply(lambda x: normalizer.normalize(x, method='lemma'))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


## Reference

### AI prompts

- Python regular expression for all formats of numeric dates
- How many records have a word starting with the letter “w”?
- can you give me step by step guide to run regex in your jupyter notebook to answer the following question: How many records make a word that starts with an alphabet and is not a URL?
- i will give you the csv file and i will give you context and list of questions, you have to aswer the question 9 for me, here is the context and questions
- Given the data info how to perform stemming with porter stemmer
- Perform lemmatization using NLTK lemmatizer. Count the number of unique words/tokens before and after lemmatization
- 1st- help me perform stemming and lemmatization, step by step guide. last- an you now guide me with complete step from beginning for the given question?