# -*- coding: utf-8 -*-
"""dcgan_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjoRcQ5o0iT5bsMkW_OuswiPI90-t86d
"""

from google.colab import drive
drive.mount('/content/drive')

import torch

if torch.cuda.is_available():
    print("GPU is available:", torch.cuda.get_device_name(0))
else:
    print("GPU not available.")

import zipfile

zip_path = "/content/drive/MyDrive/processed.zip"
extract_path = "/content/processed"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os
import time
import json
import torch
import torchvision
from torch import nn
from torchvision import transforms, datasets
from torch.utils.data import DataLoader, Subset
import matplotlib.pyplot as plt
from torchvision.utils import make_grid
from datetime import timedelta
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
import torch
import random
from collections import defaultdict

image_size = 128
batch_size = 128
sample_size = 50000
epochs = 150

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

full_dataset = datasets.ImageFolder(root="/content/processed/processed/train", transform=transform)

classes_to_keep = ['food', 'drink', 'inside', 'outside']
class_to_idx = full_dataset.class_to_idx
idx_to_class = {v: k for k, v in class_to_idx.items()}

class_indices = defaultdict(list)
for idx, (_, label) in enumerate(full_dataset.samples):
    class_name = full_dataset.classes[label]
    if class_name in classes_to_keep:
        class_indices[class_name].append(idx)

sample_per_class = sample_size // len(classes_to_keep)
final_indices = []
for cls in classes_to_keep:
    cls_indices = class_indices[cls]
    if len(cls_indices) < sample_per_class:
        raise ValueError(f"Not enough samples in class '{cls}' to sample {sample_per_class}")
    final_indices.extend(random.sample(cls_indices, sample_per_class))

dataset = Subset(full_dataset, final_indices)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=0)

print("Classes used:", classes_to_keep)
print(f"Total samples used: {len(dataset)}")
print(f"Samples per class: {sample_per_class}")

class Generator(nn.Module):
    def __init__(self, z_dim=100, channels=3, features=64):
        super().__init__()
        self.net = nn.Sequential(
            nn.ConvTranspose2d(z_dim, features * 16, 4, 1, 0, bias=False),
            nn.BatchNorm2d(features * 16),
            nn.LeakyReLU(0.2, inplace=True),

            nn.ConvTranspose2d(features * 16, features * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(features * 8),
            nn.LeakyReLU(0.2, inplace=True),

            nn.ConvTranspose2d(features * 8, features * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(features * 4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.ConvTranspose2d(features * 4, features * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(features * 2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.ConvTranspose2d(features * 2, features, 4, 2, 1, bias=False),
            nn.BatchNorm2d(features),
            nn.LeakyReLU(0.2, inplace=True),

            nn.ConvTranspose2d(features, channels, 4, 2, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, x):
        return self.net(x)

class Discriminator(nn.Module):
    def __init__(self, channels=3, features=64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(channels, features, 4, 2, 1, bias=False),  # 128 -> 64
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(features, features * 2, 4, 2, 1, bias=False),  # 64 -> 32
            nn.BatchNorm2d(features * 2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(features * 2, features * 4, 4, 2, 1, bias=False),  # 32 -> 16
            nn.BatchNorm2d(features * 4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(features * 4, 1, 4, 1, 0, bias=False),  # 16 -> 13
            nn.Sigmoid(),
            nn.AdaptiveAvgPool2d((1, 1))
        )

    def forward(self, x):
        return self.net(x).view(-1, 1)

device = "cuda" if torch.cuda.is_available() else "cpu"
z_dim = 100
lr = 2e-4
epochs = 50
sample_size = 10000
batch_size = 64

G = Generator(z_dim=z_dim).to(device)
D = Discriminator().to(device)


criterion = nn.BCELoss()
optimizer_G = torch.optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_D = torch.optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.999))

fixed_noise = torch.randn(25, z_dim, 1, 1, device=device)
overall_start = time.time()


for epoch in range(epochs):
    epoch_start = time.time()

    for real, _ in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}", leave=False):
        real = real.to(device, non_blocking=True)
        batch_size = real.size(0)

        noise = torch.randn(batch_size, z_dim, 1, 1, device=device)
        fake = G(noise)

        real_labels = torch.ones(batch_size, 1, device=device)
        fake_labels = torch.zeros(batch_size, 1, device=device)

        D_real = D(real)
        D_fake = D(fake.detach())
        d_loss = criterion(D_real, real_labels) + criterion(D_fake, fake_labels)
        optimizer_D.zero_grad()
        d_loss.backward()
        optimizer_D.step()

        fake = G(noise)
        g_loss = criterion(D(fake), real_labels)
        optimizer_G.zero_grad()
        g_loss.backward()
        optimizer_G.step()

    epoch_secs = time.time() - epoch_start
    total_secs = time.time() - overall_start
    avg_epoch = total_secs / (epoch + 1)
    remaining = avg_epoch * (epochs - epoch - 1)

    print(f"Epoch {epoch+1:02d}: D_loss={d_loss.item():.4f}  G_loss={g_loss.item():.4f}  "
          f"epoch {timedelta(seconds=int(epoch_secs))}  ETA {timedelta(seconds=int(remaining))}")

    if (epoch + 1) % 10 == 0 or epoch == epochs - 1:
        with torch.no_grad():
            fake_images = G(fixed_noise).detach().cpu()
        grid = make_grid(fake_images, nrow=5, normalize=True)
        plt.figure(figsize=(6, 6))
        plt.imshow(grid.permute(1, 2, 0))
        plt.axis("off")
        plt.title(f"Generated Images @ Epoch {epoch+1}")
        os.makedirs("generated", exist_ok=True)
        plt.savefig(f"generated/DCGAN_epoch_{epoch+1}.png")
        plt.show()

print("Training complete.")
total_training_time = time.time() - overall_start
print(f"\nTotal training time: {timedelta(seconds=int(total_training_time))}")

labels = ['food', 'drink', 'inside', 'outside']
G.eval()

fake_images = []
for _ in labels:
    z = torch.randn(1, z_dim, 1, 1, device=device)
    with torch.no_grad():
        fake_img = G(z).cpu()
    fake_images.append(fake_img)

def get_one_real_image_per_class(dataloader, target_labels):
    found = {}
    for imgs, lbls in dataloader:
        for img, lbl in zip(imgs, lbls):
            cls_name = full_dataset.classes[lbl]
            if cls_name in target_labels and cls_name not in found:
                found[cls_name] = img
            if len(found) == len(target_labels):
                return found
    return found

real_images_dict = get_one_real_image_per_class(dataloader, labels)

fig, axes = plt.subplots(2, len(labels), figsize=(4*len(labels), 8))
for i, cls in enumerate(labels):
    fake = fake_images[i][0] * 0.5 + 0.5
    axes[1, i].imshow(fake.permute(1, 2, 0).numpy())
    axes[1, i].set_title(f"Generated: {cls}")
    axes[1, i].axis("off")

plt.tight_layout()
plt.show()

!pip install torchmetrics

os.makedirs("model_weights", exist_ok=True)
torch.save({
    'generator_state_dict': G.state_dict(),
    'discriminator_state_dict': D.state_dict(),
    'z_dim': z_dim,
    'image_size': image_size,
    'batch_size': batch_size,
    'sample_size': sample_size,
    'epochs': epochs,
    'class_labels': labels,
    'model_type': 'DCGAN',
    'transform_description': "ToTensor + Normalize([0.5]*3, [0.5]*3)"
}, "model_weights/DCGAN_checkpoint.pth")

print("Model and config saved to 'model_weights/DCGAN_checkpoint.pth'")

!pip install -q lime

import numpy as np
import matplotlib.pyplot as plt
from lime import lime_image
from skimage.segmentation import mark_boundaries
from torchvision import transforms

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

D.eval()

real_img, _ = next(iter(dataloader))
real_img = real_img[0].unsqueeze(0).to(device)

noise = torch.randn(1, z_dim, 1, 1, device=device)
fake_img = G(noise).detach().to(device)

explainer = lime_image.LimeImageExplainer()

def lime_predict(images_np):
    imgs = images_np.astype(np.float32) / 255.0
    imgs = (imgs - 0.5) / 0.5
    imgs = torch.tensor(imgs.transpose((0, 3, 1, 2)), dtype=torch.float32)
    with torch.no_grad():
        preds = D(imgs.to(device)).cpu().numpy()
    return preds

def run_lime_and_plot(img_tensor, title="Image"):
    img_np = (img_tensor.squeeze().cpu() * 0.5 + 0.5).permute(1, 2, 0).numpy()
    img_np_uint8 = (img_np * 255).astype(np.uint8)
    explanation = explainer.explain_instance(
        image=img_np_uint8,
        classifier_fn=lime_predict,
        top_labels=1,
        hide_color=0,
        num_samples=1000
    )
    temp, mask = explanation.get_image_and_mask(
        label=explanation.top_labels[0],
        positive_only=True,
        num_features=5,
        hide_rest=False
    )
    plt.figure(figsize=(5, 5))
    plt.imshow(mark_boundaries(temp, mask))
    plt.title(title)
    plt.axis("off")
    plt.show()

run_lime_and_plot(real_img, title="LIME - Real Image")
run_lime_and_plot(fake_img, title="LIME - Fake Image")

!pip install optuna

import optuna
from optuna.trial import Trial
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
from torchvision.utils import make_grid
import matplotlib.pyplot as plt
import os
import random
import numpy as np

param_space = {
    "z_dim": [64, 100, 128],
    "features": [32, 64],
    "lr": [0.0002, 0.00005],
    "beta1": [0.5, 0.7]
}

def sample_hparams():
    return {
        "z_dim": random.choice(param_space["z_dim"]),
        "features": random.choice(param_space["features"]),
        "lr": random.choice(param_space["lr"]),
        "beta1": random.choice(param_space["beta1"])
    }

def quick_train(hparams):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    G = Generator(z_dim=hparams['z_dim'], features=hparams['features']).to(device)
    D = Discriminator(features=hparams['features']).to(device)

    optimizer_G = optim.Adam(G.parameters(), lr=hparams['lr'], betas=(hparams['beta1'], 0.999))
    optimizer_D = optim.Adam(D.parameters(), lr=hparams['lr'], betas=(hparams['beta1'], 0.999))
    criterion = nn.BCELoss()

    batch_size = 32
    z = torch.randn(batch_size, hparams['z_dim'], 1, 1).to(device)
    fake_imgs = G(z)
    real_imgs = torch.randn(batch_size, 3, 128, 128).to(device)

    real_labels = torch.ones(batch_size, 1).to(device)
    fake_labels = torch.zeros(batch_size, 1).to(device)
    D_loss_real = criterion(D(real_imgs), real_labels)
    D_loss_fake = criterion(D(fake_imgs.detach()), fake_labels)
    D_loss = D_loss_real + D_loss_fake
    optimizer_D.zero_grad()
    D_loss.backward()
    optimizer_D.step()

    G_loss = criterion(D(fake_imgs), real_labels)
    optimizer_G.zero_grad()
    G_loss.backward()
    optimizer_G.step()

    return D_loss.item(), G_loss.item()

results = []
for i in range(5):
    hparams = sample_hparams()
    d_loss, g_loss = quick_train(hparams)
    hparams['D_loss'] = d_loss
    hparams['G_loss'] = g_loss
    results.append(hparams)
    print(f"Trial {i+1}: {hparams}")

import pandas as pd
import matplotlib.pyplot as plt

results_df = pd.DataFrame(results)

best_config = results_df.sort_values(by="G_loss").iloc[0]
print("Best Hyperparameter Configuration:\n", best_config)

plt.figure(figsize=(10, 5))
plt.plot(results_df.index, results_df["G_loss"], marker='o', label='Generator Loss')
plt.plot(results_df.index, results_df["D_loss"], marker='o', label='Discriminator Loss')
plt.title("DCGAN Tuning Results")
plt.xlabel("Trial")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

